#ifndef ROBSCALE_QNSN_TUNED_THRESHOLDS_H
#define ROBSCALE_QNSN_TUNED_THRESHOLDS_H

// Auto-generated by tools/tune_thresholds.cpp
constexpr size_t TUNED_SORT_BOOST_THRESHOLD = 2048;
constexpr size_t TUNED_QN_EXACT_THRESHOLD = 64;

#endif // ROBSCALE_QNSN_TUNED_THRESHOLDS_H
